import java.awt.Color;

public class Logo extends PixelComponent {

    public Logo(int x, int y, int z) {
        super(x, y, z);
    }

    public Color[][] getPixels() {

        // sorry about this

        Color[][] pixels = {{Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray},
        {Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.yellow,Color.darkGray},
        {Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.yellow,Color.yellow,Color.yellow,Color.darkGray,Color.darkGray},
        {Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray,Color.darkGray}};

        return pixels;
        
    }

}